fix: upload to browser stack

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -102,6 +102,20 @@ jobs:
         uses: actions/download-artifact@v2
         with:
           name: AdTech-SampleApp.apk
-      - name: Uploading on browser stack
-        run: |
-          curl -u "ashishgupta_VUsqyD:tMJyNZgEQv2wYrrJxAJK" -X POST "https://api-cloud.browserstack.com/app-live/upload" -F "file=@/home/runner/work/github-actions-calc/github-actions-calc/app-debug.apk"
+      # Upload app to BrowserStack and set app url in an environment variable.
+      # Here replace app-debug.apk with name of your apk.
+      - run:
+          name: App upload and Set app id in environment variable.
+          command: |
+            APP_UPLOAD_RESPONSE=$(curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@/home/runner/work/github-actions-calc/github-actions-calc/app-debug.apk")
+            APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
+            if [ $APP_ID != null ]; then
+              echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
+              echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
+              source $BASH_ENV;
+              echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
+            else
+              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+              exit 1;
+            fi
