fix: upload to browser stack

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -103,16 +103,16 @@ jobs:
         with:
           name: AdTech-SampleApp.apk
       - name: App upload and Set app id in environment variable.
-          run: |
-            APP_UPLOAD_RESPONSE=$(curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@/home/runner/work/github-actions-calc/github-actions-calc/app-debug.apk")
-            APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
-            if [ $APP_ID != null ]; then
-              echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
-              echo "export BROWSERSTACK_APP_ID=$APP_ID" >> "${BASH_ENV}";
-              source $BASH_ENV;
-              echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
-            else
-              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
-              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
-              exit 1;
-            fi
+        run: |
+          APP_UPLOAD_RESPONSE=$(curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@/home/runner/work/github-actions-calc/github-actions-calc/app-debug.apk")
+          APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
+          if [ $APP_ID != null ]; then
+            echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
+            echo "export BROWSERSTACK_APP_ID=$APP_ID" >> "${BASH_ENV}";
+            source $BASH_ENV;
+            echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
+          else
+            UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+            echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+            exit 1;
+          fi
